apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: cy9bngryg-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:fd62b928f32835c76310b2cf2ef7caac120e33fd@sha256:c838e1a051ef12379b8b194470f5ecdaa7fb05870888cd89eccd29efec285d4d
          name: container-image
