apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cy9bngryg-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cy9bngryg-go 
  name: cy9bngryg-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cy9bngryg-go 
